### ISSUE TITLE
The URL bar showing/hiding clears the canvas by default

### ISSUE THREAD

**Issue by lifzgreat** [michaeldzjap/react-signature-pad-wrapper#5]
The default `redrawOnResize` property is set to false which is good. However, the URL bar shows/hides when scrolling a page which fires a resize and clears the canvas. If you have a form that needs to scroll, the signature pad clears itself before being able to submit it. You don't want to have to be forced to redraw on resize because of the data degradation each time. I can't think of a way to address the issue though!

Edit: would it work to store the dimensions and check to see if they've changed inside the resize event rather than wiping the canvas on all resize events? The URL bar causes a resize event to fire but the dimensions haven't actually changed.

**Comment by michaeldzjap** [comment]
@lifzgreat Is there a specific device/browser you are experiencing this with? But yeah, I think this is a hard one to solve easily/universally.

With regards to the data degradation when redrawing. This would only be an issue if your canvas actually changes dimensions. Is this indeed the case? I guess so, otherwise the resize event would not be fired, but I seem to recall some (older) mobile devices sometimes fire resize events inappropriately. If the change in dimension is not too large then the data will not degrade much, but its not ideal no.

**Comment by lifzgreat** [comment]
@michaeldzjap Thanks for the quick reply. This is a Google Pixel XL on Android 8.1.

I'm starting to think if the dimensions are stored when the resize event fires, they can be compared to the most recently known dimensions. Then you can only call call `clear()` if they differ. Will that work?

**Comment by michaeldzjap** [comment]
I'm not sure if that will solve your problem to be honest. If the resize event is called because your canvas dimensions actually did change when the URL bar pops up then that won't work obviously, because your content will be cleared.

If the resize event is "falsely" called and hence, your canvas dimensions did not change then your proposal would work. But apart from some efficiency gain (which probably would be negligible) there would be no other benefit over setting the `redrawOnResize` to `true`, because if you're canvas dimensions stay the same then redrawing the signature should not degrade the quality of your original drawing.

**Comment by lifzgreat** [comment]
I guess it's not necessarily "falsely" firing, that's how Android has decided to handle URL bar showing/hiding. We can't change that, however, we can keep from unnecessarily calling the `clear()` function in the `resize()` event. A `resize()` event firing doesn't necessarily mean the window dimensions have changed as we're seeing here (or for another example, think of someone manually firing it).

If you check the dimensions against the current last known dimensions it does fix this issue. I can try to submit a PR if you don't mind (I've never done it before) - it doesn't hurt anything, it just stops unnecessary canvas scaling.

**Comment by michaeldzjap** [comment]
Yes, you make a good point actually. The resize handler doesn't need to be fired when the dimensions of the canvas do not change. I think that makes sense and I don't think it would cause any unforeseen problems. You can submit a PR if you want, but I can do this also myself. It's not a lot of work.

**Comment by lifzgreat** [comment]
Thank you! Doh...I couldn't figure out how to submit it :) Here is all I did:

1. Add `if (this._canvas && this._canvas.offsetWidth === this.canvasWidth && this._canvas.offsetHeight === this.canvasHeight) return;` as the first line of `scaleCanvas()`
2. Add `this.canvasWidth = width;` and `this.canvasHeight = height;` under where you set width/height in `scaleCanvas()`

**Comment by lifzgreat** [comment]
Thank you for merging, it's working perfectly now. I noticed it doesn't like if there's a border because outerWidth/outerHeight counts borders in your calculation. Maybe innerWidth/innerHeight would work better but for now I just removed the border. Thanks again, wonderful tool.
