### ISSUE TITLE
Please don’t use class'es

### ISSUE THREAD

**Issue by MariuzM** [michaeldzjap/react-signature-pad-wrapper#64]
Its 2024 can we please stop using Classes? 
Also I'm sure its me but finding difficult to resize it with outer div, either i get offset of input or it does not work or it overlaps with other elements.

**Comment by MariuzM** [comment]
My cursor is here but then it paints at bottom 
<img width="453" alt="image" src="https://github.com/user-attachments/assets/29754f9d-f6d3-4eab-a8ae-0b178a19696a">

```
import SignaturePad from 'react-signature-pad-wrapper'

export const App = () => {
	return (
		<div>
			<SignaturePad height={200} width={200} />
			<div style={{ backgroundColor: 'red', height: '100px', width: '100%' }}>Component</div>
		</div>
	)
}
```

**Comment by MariuzM** [comment]
The sizing prop its not px so i don’t know what it is because its not 500px as it should be 
<img width="1282" alt="image" src="https://github.com/user-attachments/assets/70f5c45d-b35c-4b8c-ac30-109a5e1292db">


This is more accurate 
![Uploading image.png…]()

**Comment by michaeldzjap** [comment]
> Its 2024 can we please stop using Classes?

What is wrong with using classes? Personally I find it a hell of a lot more clear than having to work with hooks and functional components and as far as I understand there isn't much (if any) difference between the two from a performance point of view. Certainly not enough difference for me to start refactoring this package to using a functional component just because "it's 2024"... If you feel strongly about it you can always contribute yourself by means of a PR and maybe I will consider merging it.

Regarding your other question; the width and height properties set the [width](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/width) and height of the canvas. However, it gets multiplied by `window.devicePixelRatio` to handle high DPI screens as suggested [here](https://github.com/szimek/signature_pad?tab=readme-ov-file#handling-high-dpi-screens).
